spring: 
  application:
    name: TICKET-SERVICE
  datasource: 
    url: jdbc:mysql://localhost:3306/TicketBook?createDatabaseIfNotExist=true
    username: root
    password: 
  jpa:
    hibernate: 
    naming: 
    physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    hibernate.ddl-auto: create
    show-sql: true
    format_sql:  true
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
server:
  port: 9999
